name: energielabel_app
description: An App from BAM

#  * Copyright 2020 Bundesanstalt für Materialforschung und -prüfung (BAM) *
#  * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
#  * You may not use this work except in compliance with theLicence.
#  * You may obtain a copy of the Licence at:
#  * * https://joinup.ec.europa.eu/software/page/eupl *
#  * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the Licence for the specific language governing permissions and limitations under the Licence.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+19

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=2.0.3"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: 1.0.2
  auto_size_text: 2.1.0
  flutter_html: 2.0.0-nullsafety.0
  dots_indicator: 2.0.0
  visibility_detector: 0.1.5
  flutter_inappwebview: 5.2.1+1
  rive: 0.6.8
  flutter_cached_pdfview: 0.3.5
  drop_cap_text: 1.0.7
  flutter_svg: 0.21.0-nullsafety.0
  qr_code_scanner: 0.4.0
  video_player: 2.0.2
  chewie: 1.0.0
  scrollable_positioned_list: 0.1.10
  responsive_layout_builder: 0.5.0

  # Architecture
  get_it: 6.0.0
  provider: 5.0.0
  rxdart: 0.25.0
  optional: 5.0.0+1
  pedantic: 1.11.0

  # Logging
  flutter_fimber: 0.6.2

  # Networking
  dio: 3.0.10
  system_proxy: 0.0.1
  json_serializable: 4.0.2
  json_annotation: 4.0.1

  # Persistence
  shared_preferences: 0.5.12+4

  # Device interaction
  package_info: 2.0.0
  url_launcher: 6.0.3
  mailto: 1.1.0
  share: 2.0.1

  # L10N
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  # misc
  collection: 1.15.0
  pdf: 3.1.0
  diacritic: 0.1.3
  synchronized: 2.2.0+2

dev_dependencies:
  build_runner: 1.11.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Adds code generation (synthetic package) support.
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/favorites/
    - assets/images/home/
    - assets/images/infothek/
    - assets/images/know_how/
    - assets/images/know_how/label_guide/
    - assets/images/know_how/label_guide/fridge_guide/
    - assets/images/know_how/regulations/
    - assets/images/know_how/glossary/
    - assets/images/know_how/why_is_there/
    - assets/images/menu/
    - assets/images/onboarding/
    - assets/images/quiz/
    - assets/json/
    - assets/css/
    - assets/html/
    - assets/pdf/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
