name: energielabel_app
description: An App from BAM

#  * Copyright 2020 Bundesanstalt für Materialforschung und -prüfung (BAM) *
#  * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
#  * You may not use this work except in compliance with theLicence.
#  * You may obtain a copy of the Licence at:
#  * * https://joinup.ec.europa.eu/software/page/eupl *
#  * Unless required by applicable law or agreed to in writing, software distributed under the Licence is distributed on an "AS IS" basis,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the Licence for the specific language governing permissions and limitations under the Licence.


publish_to: 'none'
version: 1.1.1+24

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.10.1"

dependencies:
  flutter:
    sdk: flutter

  # UI
  auto_size_text: 3.0.0
  flutter_html: 2.1.5
  dots_indicator: 2.1.0
  visibility_detector: 0.2.2
  rive: 0.8.1
  native_pdf_view: 6.0.0+1
  drop_cap_text: 1.1.3
  flutter_svg: 0.22.0
  qr_code_scanner: 0.7.0
  video_player: 2.2.18
  scrollable_positioned_list: 0.2.3
  responsive_layout_builder: 0.5.0

  # Architecture
  get_it: 7.2.0
  provider: 6.0.2
  rxdart: 0.27.3

  # Networking
  json_serializable: 6.1.4
  json_annotation: 4.4.0

  # Persistence
  shared_preferences: 2.0.13
  path_provider: any

  # Device interaction
  package_info: 2.0.2
  url_launcher: 6.0.20
  mailto: 2.0.0
  share_plus: 3.0.5

  # L10N
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  # misc
  collection: 1.15.0
  pdf: 3.7.1
  csv: 5.0.1
  diacritic: 0.1.3
  synchronized: 3.0.0

dev_dependencies:
  flutter_lints: 1.0.4
  build_runner: 2.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Adds code generation (synthetic package) support.
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/favorites/
    - assets/images/home/
    - assets/images/infothek/
    - assets/images/know_how/
    - assets/images/know_how/label_guide/
    - assets/images/know_how/label_guide/fridge_guide/
    - assets/images/know_how/label_guide/light_adviser/
    - assets/images/know_how/regulations/
    - assets/images/know_how/glossary/
    - assets/images/know_how/why_is_there/
    - assets/images/menu/
    - assets/images/onboarding/
    - assets/images/quiz/
    - assets/json/
    - assets/css/
    - assets/html/
    - assets/pdf/
    - assets/animations/
    - assets/fonts/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
